/** The shop's calendar: three months of workshops, popups and community nights. */

export type EventCategory = "workshop" | "community" | "popup";

export type CalendarEvent = {
  id: string;
  /** ISO date, no time zone — the shop's own local day. */
  date: string;
  /** 24-hour "HH:MM". */
  start: string;
  end: string;
  category: EventCategory;
  title: string;
  host: string;
  /** 0 means free. */
  price: number;
  /** 0 means drop-in: no sign-up, no seat limit. */
  capacity: number;
  /** Seats already taken by other people. */
  taken: number;
  description: string;
};

export const CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: "zine-fair",
    date: "2026-09-19",
    start: "11:00",
    end: "16:00",
    category: "community",
    title: "Zine Fair",
    host: "Ninth St. Press",
    price: 0,
    capacity: 0,
    taken: 0,
    description: "Tables of small-press zines, comics and prints from East Bay makers. Bring a few bucks and a tote.",
  },
  {
    id: "wheel-1",
    date: "2026-09-24",
    start: "18:30",
    end: "20:30",
    category: "workshop",
    title: "Intro to Wheel Throwing",
    host: "Rosa Delgado",
    price: 65,
    capacity: 8,
    taken: 6,
    description: "Center, open and pull your first cylinders. Clay, tools and one firing included.",
  },
  {
    id: "clay-night",
    date: "2026-09-27",
    start: "18:00",
    end: "21:00",
    category: "workshop",
    title: "Clay Night",
    host: "Rosa Delgado",
    price: 40,
    capacity: 12,
    taken: 9,
    description: "Hand-build a planter or a pinch-pot set. Glazed and fired pieces ready to pick up in two weeks.",
  },
  {
    id: "screen-1",
    date: "2026-10-01",
    start: "18:30",
    end: "21:00",
    category: "workshop",
    title: "Beginner Screenprinting",
    host: "Ninth St. Press",
    price: 55,
    capacity: 10,
    taken: 4,
    description: "Burn a screen and pull a two-color print on a tote. All inks and blanks provided.",
  },
  {
    id: "tools-101a",
    date: "2026-10-03",
    start: "10:00",
    end: "11:30",
    category: "workshop",
    title: "Tool Library 101: Drills + Drivers",
    host: "Tool library",
    price: 0,
    capacity: 12,
    taken: 7,
    description: "How to pick the right bit, drive a screw straight and check out tools from the library.",
  },
  {
    id: "swap",
    date: "2026-10-04",
    start: "10:00",
    end: "14:00",
    category: "community",
    title: "Swap Meet",
    host: "Neighbors",
    price: 0,
    capacity: 0,
    taken: 0,
    description: "Bring what you are done with, take what you need. Clothes, books, houseplants, kitchen stuff.",
  },
  {
    id: "dye-1",
    date: "2026-10-08",
    start: "18:00",
    end: "20:30",
    category: "workshop",
    title: "Natural Dye Basics",
    host: "Hana Ito",
    price: 60,
    capacity: 10,
    taken: 10,
    description: "Dye a silk scarf with onion skin, indigo and avocado pits. Take home your dye notes.",
  },
  {
    id: "kids-clay",
    date: "2026-10-10",
    start: "10:00",
    end: "11:00",
    category: "workshop",
    title: "Kids Clay Hour",
    host: "Rosa Delgado",
    price: 20,
    capacity: 10,
    taken: 3,
    description: "Ages 5–10 with a grown-up. Squish, pinch and make a tiny creature.",
  },
  {
    id: "supper",
    date: "2026-10-11",
    start: "18:00",
    end: "21:00",
    category: "popup",
    title: "Supper Club Popup",
    host: "Guest chef",
    price: 45,
    capacity: 12,
    taken: 11,
    description: "A long-table dinner with neighbors. Three courses, seasonal and local, from this month's guest chef.",
  },
  {
    id: "dumpling",
    date: "2026-10-12",
    start: "11:00",
    end: "14:00",
    category: "popup",
    title: "Dumpling Popup",
    host: "Guest vendor",
    price: 0,
    capacity: 0,
    taken: 0,
    description: "Hand-folded dumplings by the tray, while they last. Walk up, no sign-up needed.",
  },
  {
    id: "mending-1",
    date: "2026-10-15",
    start: "18:30",
    end: "20:30",
    category: "community",
    title: "Mending Circle",
    host: "Hana Ito",
    price: 0,
    capacity: 14,
    taken: 5,
    description: "Bring a hole, a rip or a loose button. We bring thread, patches and company.",
  },
  {
    id: "letter-1",
    date: "2026-10-17",
    start: "13:00",
    end: "15:30",
    category: "workshop",
    title: "Hand-Lettered Signs",
    host: "Ninth St. Press",
    price: 50,
    capacity: 10,
    taken: 2,
    description: "Brush lettering basics, then paint a small wooden sign to take home.",
  },
  {
    id: "wheel-2",
    date: "2026-10-22",
    start: "18:30",
    end: "20:30",
    category: "workshop",
    title: "Intro to Wheel Throwing",
    host: "Rosa Delgado",
    price: 65,
    capacity: 8,
    taken: 1,
    description: "Center, open and pull your first cylinders. Clay, tools and one firing included.",
  },
  {
    id: "repot",
    date: "2026-10-24",
    start: "11:00",
    end: "12:30",
    category: "workshop",
    title: "Houseplant Repotting",
    host: "Hennai Home + Garden",
    price: 35,
    capacity: 12,
    taken: 4,
    description: "Bring a root-bound plant. Leave with it happy in a new pot and fresh soil.",
  },
  {
    id: "maker-mkt",
    date: "2026-10-25",
    start: "10:00",
    end: "15:00",
    category: "community",
    title: "Maker Market",
    host: "Local makers",
    price: 0,
    capacity: 0,
    taken: 0,
    description: "Twenty-plus local makers in and around the shop. Free to browse.",
  },
  {
    id: "lino",
    date: "2026-10-29",
    start: "18:30",
    end: "20:30",
    category: "workshop",
    title: "Linocut Halloween Cards",
    host: "Ninth St. Press",
    price: 40,
    capacity: 10,
    taken: 6,
    description: "Carve a block and print a stack of spooky cards.",
  },
  {
    id: "costume",
    date: "2026-10-31",
    start: "12:00",
    end: "15:00",
    category: "community",
    title: "Costume Repair Drop-In",
    host: "Tool library",
    price: 0,
    capacity: 0,
    taken: 0,
    description: "Glue guns, sewing machines and help on hand for last-minute fixes.",
  },
  {
    id: "taco-1",
    date: "2026-11-01",
    start: "12:00",
    end: "15:00",
    category: "popup",
    title: "Taco Popup",
    host: "Guest vendor",
    price: 0,
    capacity: 0,
    taken: 0,
    description: "Tacos out front for the afternoon. Walk up, no sign-up needed.",
  },
  {
    id: "mugs",
    date: "2026-11-05",
    start: "18:00",
    end: "21:00",
    category: "workshop",
    title: "Stoneware Mugs",
    host: "Rosa Delgado",
    price: 70,
    capacity: 8,
    taken: 2,
    description: "Hand-build and handle two mugs. Glaze night is included.",
  },
  {
    id: "tools-101b",
    date: "2026-11-07",
    start: "10:00",
    end: "11:30",
    category: "workshop",
    title: "Tool Library 101: Sanders + Saws",
    host: "Tool library",
    price: 0,
    capacity: 12,
    taken: 3,
    description: "Safe, confident use of orbital sanders, jigsaws and a mitre saw.",
  },
  {
    id: "wreath",
    date: "2026-11-14",
    start: "13:00",
    end: "15:00",
    category: "workshop",
    title: "Dried Flower Wreaths",
    host: "Hennai Home + Garden",
    price: 45,
    capacity: 12,
    taken: 5,
    description: "Build a wreath from dried flowers and grasses grown in the East Bay.",
  },
  {
    id: "bake-1",
    date: "2026-11-15",
    start: "09:00",
    end: "12:00",
    category: "popup",
    title: "Bake Sale Popup",
    host: "Guest baker",
    price: 0,
    capacity: 0,
    taken: 0,
    description: "Pies, buns and whatever came out of the oven that morning.",
  },
  {
    id: "mending-2",
    date: "2026-11-19",
    start: "18:30",
    end: "20:30",
    category: "community",
    title: "Mending Circle",
    host: "Hana Ito",
    price: 0,
    capacity: 14,
    taken: 2,
    description: "Bring a hole, a rip or a loose button. We bring thread, patches and company.",
  },
  {
    id: "holiday-mkt",
    date: "2026-11-21",
    start: "10:00",
    end: "16:00",
    category: "community",
    title: "Holiday Maker Market",
    host: "Local makers",
    price: 0,
    capacity: 0,
    taken: 0,
    description: "Gifts made down the street. Free to browse, cocoa from a popup vendor.",
  },
];

export const CATEGORIES: Record<
  EventCategory,
  { label: string; color: string; ink: string }
> = {
  workshop: {
    label: "Workshop",
    color: "var(--color-ecs-pink)",
    ink: "#4a1f30",
  },
  community: {
    label: "Community",
    color: "var(--color-ecs-marigold)",
    ink: "#22201c",
  },
  popup: {
    label: "Food popup",
    color: "var(--color-ecs-magenta)",
    ink: "#ffffff",
  },
};

/** The calendar only navigates across the months that actually have events. */
export const FIRST_MONTH = { year: 2026, month: 8 };
export const LAST_MONTH = { year: 2026, month: 10 };

/** Where a visitor's own seat reservations are remembered, per browser. */
export const SIGNUPS_STORAGE_KEY = "ecs-cal-signups-v1";
